#!/bin/bash

export AZURE_STORAGE_ACCOUNT="pithub"
export AZURE_STORAGE_ACCESS_KEY="dGs3x4XF2M7bwJN9GtU0HaahFzqa77rWU/TWl8Oryqon93V28sexQ80V8V6PNedgEMhVu3C2eEBGcWUtFDcEUA=="
export AZURE_CONTAINER_NAME="nvm4zqwmtesttest"
echo $AZURE_STORAGE_ACCOUNT
echo $AZURE_STORAGE_ACCESS_KEY
echo $AZURE_CONTAINER_NAME
code .